dresser/website/auth.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from .models import User, Cloth
from . import db
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
import base64

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(name=name).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                flash('Logged in successfully👍', category='success')
                return redirect(url_for('views.home'))
            else:
                flash('Password Incorrect☹', category='error')
                return redirect(url_for('auth.login'))
        else:
            flash('User does not exist', category='error')
            return redirect(url_for('auth.login'))



    return render_template('login.html', user=current_user)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        name = request.form.get('username').lower()
        password = request.form.get('password')
        password_confirm = request.form.get('password2')
        image = request.files['p-image'].read()
        encoded_image = base64.b64encode(image).decode('utf-8')
        gender = request.form.get('gender')

        user = User.query.filter_by(name=name).first()
        if user:
            flash('A user with this name already exists☹', category='error')
        else:
            if password != password_confirm:
                flash('Passwords do not match', category='error')
            elif len(name) < 3:
                flash('Name should be at least 3 characters', category='error')
            elif len(password) < 4:
                flash('Password should be at least 4 characters', category='error')
            elif gender == None:
                flash('Please select a gender', category='error')
            else:
                if len(encoded_image) < 1:
                    new_user = User(name=name, password=generate_password_hash(password, method='sha256'), gender=gender)
                else:
                    new_user = User(name=name, password=generate_password_hash(password, method='sha256'), profile_pic=encoded_image, gender=gender)
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user, remember=True)
                flash('Account has been created successfully👍', category='success')
                return redirect(url_for('views.home'))


    return render_template('signup.html', user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

dresser/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from .models import Cloth, User, Log, Combination
from . import db
import base64
import random

views = Blueprint('views', __name__)

@views.route('/')
@views.route('/home')
@login_required
def home():
    uncommitted_cloths = Cloth.query.filter_by(user_id=current_user.id, isCommitted=False).all()
    uncommitted_cloths.reverse()

    return render_template('base.html', user=current_user, unc_cloths=uncommitted_cloths)

@views.route('/profile')
@login_required
def profile():
    no_pic = True
    if current_user.profile_pic != None:
        no_pic = False
    combos = Combination.query.all()
    combos.reverse()
    cloths = len(Cloth.query.filter_by(user_id=current_user.id).all())
    unc_cloths = len(Cloth.query.filter_by(user_id=current_user.id, isCommitted=False).all())
    comm_cloths = len(Cloth.query.filter_by(user_id=current_user.id, isCommitted=True).all())
    tops = len(Cloth.query.filter_by(user_id=current_user.id, type='top').all())
    bottoms = len(Cloth.query.filter_by(user_id=current_user.id, type='bottom').all())

    possible_combos = len(Cloth.query.filter_by(user_id=current_user.id, type='top', isCommitted=True).all())*len(Cloth.query.filter_by(user_id=current_user.id, type='bottom', isCommitted=True).all())
    available_combos = possible_combos - len(combos)
    blacklisted_combos = len(Combination.query.filter_by(user_id=current_user.id, isBlacklisted=True).all())
    used_combos = len(Combination.query.filter_by(user_id=current_user.id, isBlacklisted=False).all())

    return render_template('profile.html',
                           user=current_user, no_pic=no_pic, cloths=cloths, unc_cloths=unc_cloths, comm_cloths=comm_cloths, tops=tops, bottoms=bottoms, combos=combos, possible_combos=possible_combos, available_combos=available_combos, blacklisted_combos=blacklisted_combos, used_combos=used_combos)

@views.route('/new_cloth', methods=['GET', 'POST'])
@login_required
def new_cloth():
    if request.method == 'POST':
        # retrieve the cloth name and description from the form data
        name = request.form.get('name')
        description = request.form.get('description')
        image = request.files['image'].read()
        encoded_image = base64.b64encode(image).decode('utf-8')
        isCommit = request.form.get('commit')
        cloth_type = request.form.get('type')
        
        if Cloth.query.filter_by(name=name).first():
            flash('Name already exists, make it unique!', category='error')
        else:
            # create a new Cloth object and save it to the database
            if isCommit:
                new_cloth = Cloth(name=name, description=description, image=encoded_image, isCommitted=True, type=cloth_type, user_id=current_user.id)
            else:
                new_cloth = Cloth(name=name, description=description, image=encoded_image, isCommitted=False, type=cloth_type, user_id=current_user.id)
            db.session.add(new_cloth)
            db.session.commit()
            new_log = Log(name=name, event='cloth create', user_id=current_user.id)
            db.session.add(new_log)
            db.session.commit()

            clothExists = Cloth.query.filter_by(description=description).first()
            if clothExists and clothExists.name != name:

                flash('This cloth has the same description as another', category='warning')
            else:
                flash('Cloth created successfuuly', category='success')
            return redirect(url_for('views.home'))

    return render_template('new_cloth.html', user=current_user)


@views.route('/backend/cloth/do-something/<int:id>')
@login_required
def cloth_gateway(id):
    cloth = Cloth.query.filter_by(id=id, user_id=current_user.id).first()
    action = request.args.get('action')
    if action == 'commit':
        cloth.isCommitted = True
        db.session.commit()
        new_log = Log(name=cloth.name, event='update', user_id=current_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash(f'{cloth.name} has been committed successfully', category='success')
        return redirect(url_for('views.home'))
    elif action == 'delete':
        db.session.delete(cloth)
        db.session.commit()
        new_log = Log(name=cloth.name, event='delete', user_id=current_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash(f'{cloth.name} has been deleted successfully', category='success')
        return redirect(url_for('views.home'))
    
@views.route('/edit/cloth/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    cloth = Cloth.query.filter_by(id=id).first()
    if request.method == 'POST':
        cloth.name = request.form.get('name')
        cloth.description = request.form.get('description')
        isCommit = request.form.get('commit')
        if isCommit:
            cloth.isCommitted = True
        else:
            cloth.isCommitted = False
        cloth.type = request.form.get('type')

        db.session.commit()
        new_log = Log(name=cloth.name, event='update', user_id=current_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash('New changes added', category='success')
        return redirect(url_for('views.home'))

    return render_template('edit.html', user=current_user, cloth=cloth)

@views.route('/log/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def log_gateway(id):
    action = request.args.get('action')
    if action == 'delete':
        log = Log.query.filter_by(user_id=current_user.id, id=id).first()
        db.session.delete(log)
        db.session.commit()
        return redirect(url_for('views.history'))
    elif action == 'delete_all':
        logs = Log.query.filter_by(user_id=current_user.id).all()
        for log in logs:
            db.session.delete(log)
        db.session.commit()
        return redirect(url_for('views.history'))

@views.route('/history')
@login_required
def history():
    logs = Log.query.filter_by(user_id=current_user.id).all()
    logs.reverse()

    return render_template('history.html', user=current_user, logs=logs)

@views.route('/backend/combo/do-something/<int:id>')
@login_required
def combo_gateway(id):
    combo = Combination.query.filter_by(id=id, user_id=current_user.id).first()
    action = request.args.get('action')
    if action == 'blacklist':
        combo.isBlacklisted = True
        db.session.commit()
        new_log = Log(event='combo update', user_id=current_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash(f'combo has been blacklisted successfully', category='success')
        return redirect(url_for('views.profile'))
    elif action == 'unblacklist':
        combo.isBlacklisted = False
        db.session.commit()
        new_log = Log(event='combo update', user_id=current_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash(f'combo has been un-blacklisted successfully', category='success')
        return redirect(url_for('views.profile'))
    elif action == 'delete':
        db.session.delete(combo)
        db.session.commit()
        new_log = Log(event='combo delete', user_id=current_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash(f'combo has been deleted successfully', category='success')
        return redirect(url_for('views.profile'))
    
@views.route('/generate/template')
@login_required
def generate_template():

    return render_template('generate_template.html', user=current_user)

@views.route('/generate')
@login_required
def generate():
    tops = Cloth.query.filter_by(user_id=current_user.id, type='top', isCommitted=True).all()
    bottoms = Cloth.query.filter_by(user_id=current_user.id, type='bottom', isCommitted=True).all()
    possible_combos = len(tops)*len(bottoms)
    available_combos = possible_combos - len(Combination.query.all())
    count = 0
    for top in tops:
        print(top.name)

    if len(tops) < 1 or len(bottoms) < 1:
        flash('There are not enough cloths. Create more or commit existing', category='warning')
        return redirect(url_for('views.generate_template'))
    else:
        combo_list = []
        top = random.choice(tops)
        bottom = random.choice(bottoms)
        comboExists = Combination.query.filter_by(top=top.name, bottom=bottom.name, user_id=current_user.id).first()
        combo_list.append([top,bottom])
        if comboExists:
            for t in tops:
                for b in bottoms:
                    if [t, b] not in combo_list:
                        combo_list.append([t, b])

            while count < available_combos and len(combo_list) < available_combos:
                top = random.choice(tops)
                bottom = random.choice(bottoms)
                comboExists = Combination.query.filter_by(top=top.name, bottom=bottom.name, user_id=current_user.id).first()
                if comboExists:
                    combo_list.append([top, bottom])

                if [top, bottom] in combo_list:
                    count+= 1
                else:
                    count = 0
                    break

            if count == available_combos and comboExists:
                flash('There are no more possible combinations. Create more cloth or commit existing', category='warning')
                return redirect(url_for('views.generate_template'))

    return render_template('generate.html', user=current_user, top=top, bottom=bottom)

@views.route('/combo/gateway/<int:top_id>/<int:bottom_id>')
@login_required
def combo_create_gateway(top_id, bottom_id):

dresser/website/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block header %}About{% endblock %}
{% block extra_styles %}
<style>
    .about-container {
        max-width: 85%;
        width: 85%;
    }

    span {
        font-size: medium;
        font-weight: bold;
    }
</style>
{% endblock %}
{% block content %}
<div class="about-container free-center mt-5">
    &emsp;&emsp;&emsp;This is a simple app prototype to help you in picking your outfits. There are six essential pages to look out for: <br>

    <p>
        • <span>Homepage</span> - displays all the cloths you have not committed[explained later]. You can then click on these cloths to either delete, edit or commit them <br>
        • <span>New cloth</span> - you concrete new cloths here <br>
        • <span>Generate</span> - you can't generate outfits(combinations) here <br>
        • <span>History</span> - shows a log of all your activities <br>
        • <span>Profile</span> - shows the very little info we have on you along with your combinations and stats <br>
        • <span>About</span> - speaks for itself <br>
    </p>
    <p>
        &emsp;&emsp;&emsp;Furthermore, to utilize the app, there are four terms you need to know - '<cite title="Source Title">cloths</cite>', '<cite title="Source Title">committing</cite>', '<cite title="Source Title">combos</cite>', '<cite title="Source Title">blackliting & using</cite>' <br>
        • <span>Cloths</span> - these are cloths that are created by you they can either be a top(shirt) or a bottom(pant). When you create a new cloth, you can decide to commit it or not <br>
        • <span>Committing</span> - any 'uncommitted' cloth would not be available when you generate a new combo. You can commit or uncommit a cloth any number of times <br>
        • <span>Combos</span> - a combo is basically a generated outfit. When you go to the 'generate' page and generates an outfit, you can click generate to create a new one, blacklist or use a combo <br>
        • <span>Blacklisting & Using</span> - blacklisting a combo means you do not want to use but you also do not want it to be suggested(generated) anymore[maybe cuz it looks hideous] while using a combo means you have accepted that particular combo <br>
    </p>
    <p>
        Thanks for reading😄
    </p>
</div class="about-container free-center mt-5">
{% endblock %}

dresser/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{{url_for('static', filename='styles.css')}}"/> -->
</head>
<body>
    {% block extra_styles %}
        <style>
            .card {
                max-width: 80%;
                width: 80%;
                max-height: 150px;
                cursor: pointer;
                overflow: hidden;
            }
        </style>
    {% endblock %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Error!</strong> {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif category == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success!</strong> {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif category == 'info' %}
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    <strong>Info!</strong> {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif category == 'warning' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Warning!</strong> {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}

    {% block nav %}
    <ul class="nav nav-tabs" align="center">
        <li class="nav-item me-3">
          <a class="nav-link active" aria-current="page" href="{{ url_for('views.home') }}">Home</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="{{ url_for('views.new_cloth') }}">New</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="{{ url_for('views.generate_template') }}">Generate</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="{{ url_for('views.history') }}">History</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="{{ url_for('views.profile') }}">Profile</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item me-3">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item me-3">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item me-3">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">Signup</a>
            </li>
        {% endif %}
    </ul>
    {% endblock %}

    {% block head %}
        <div class="grp mt-2" align="center">
            <h2>{% block header %}Uncommited Cloths{% endblock %}</h2>
            <div id="underline"></div>
        </div>
    {% endblock %}

    {% block content %}
    {% for cloth in unc_cloths %}
        <div class="card mb-3 mt-3 center" data-bs-toggle="modal" data-bs-target="#{{ cloth.id }}clothModal">
            <div class="row g-flex">
                <div class="col-8 row-sm-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ cloth.name }}</h5>
                        <p class="card-text">{{ cloth.description }}</p>
                        <p class="card-text"><small class="text-muted">{{ cloth.time }}</small></p>
                    </div>
                </div>

                <div class="col-4 row-sm-4">
                    <img src="data:image/png;base64,{{ cloth.image }}" class="img-fluid rounded-start" alt="{{ cloth.name }} image">
                </div>
            </div>
        </div>

        <div class="modal free-center" tabindex="-1" id="{{ cloth.id }}clothModal">
            <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">{{ cloth.name }}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img src="data:image/png;base64,{{ cloth.image }}" class="img-fluid rounded-start mb-2" alt="{{ cloth.name }} image">
                  <p>{{ cloth.description }}</p>
                </div>
                <div class="modal-footer space-between-flex">
                    <div>
                            <a href="{{ url_for('views.cloth_gateway', id=cloth.id, action='delete') }}" class="no-deco"><button type="button" class="btn btn-danger">Delete</button></a>
                    </div>
                    <div>
                        <a href="{{ url_for('views.edit', id=cloth.id) }}" class="no-deco"><button type="button" class="btn btn-secondary">E</button></a>
                        <a href="{{ url_for('views.cloth_gateway', id=cloth.id, action='commit') }}" class="no-deco"><button type="button" class="btn btn-primary" data-bs-dismiss="modal">Commit</button></a>
                    </div>
                </div>
              </div>
            </div>
        </div>
    {% endfor %}
    {% endblock %}
    <script
        type="text/javascript"
        src="{{ url_for('static', filename='app.js') }}"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>
</html>

dresser/website/templates/generate.html
{% extends 'base.html' %}
{% block title %}Generate{% endblock %}
{% block extra_styles %}
<style>
    span {
        font-size: 50px;
        font-family: Arial, Helvetica, sans-serif;
        font-weight: bolder;
        font-style: oblique;
    }

    .card-text {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
</style>
{% endblock %}
{% block header %}Generate{% endblock %}
{% block content %}
<div class="display-container free-center">
    <div class="card" style="width: 18rem;">
        <img src="data:image/png;base64,{{ top.image }}" class="card-img-top" alt="{{ top.name }}">
        <div class="card-body" style="position: relative;">
          <p class="card-text">{{ top.name }}</p>
        </div>
    </div>
    <span>+</span>
    <div class="card" style="width: 18rem;">
        <img src="data:image/png;base64,{{ bottom.image }}" class="card-img-top" alt="{{ bottom.name }}">
        <div class="card-body" style="position: relative;">
          <p class="card-text">{{ bottom.name }}</p>
        </div>
    </div>
</div>
<div class="mt-5 free-center">
    <a href="{{ url_for('views.combo_create_gateway', top_id=top.id, bottom_id=bottom.id, action='blacklist') }}" class="no-deco"><button class="btn btn-dark me-3">Blacklist</button></a>
    <a href="{{ url_for('views.generate') }}" class="no-deco"><button class="btn btn-primary me-3">Generate</button></a>
    <a href="{{ url_for('views.combo_create_gateway', top_id=top.id, bottom_id=bottom.id, action='use') }}" class="no-deco"><button class="btn btn-success me-3">Use Combo</button></a>
</div>
{% endblock %}

dresser/website/templates/generate_template.html
{% extends 'base.html' %}
{% block title %}Generate{% endblock %}
{% block extra_styles %}
<style>
    span {
        font-size: 100px;
        font-family: Arial, Helvetica, sans-serif;
        font-weight: bolder;
        font-style: oblique;
    }

    .card-text {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
</style>
{% endblock %}
{% block header %}Generate{% endblock %}
{% block content %}
<div class="display-container free-center">
    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body" style="position: relative;">
          <p class="card-text">Top</p>
        </div>
    </div>
    <span>+</span>
    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body" style="position: relative;">
          <p class="card-text">Bottom</p>
        </div>
    </div>
</div>
<div class="mt-5 free-center">
    <button class="btn btn-dark me-3" disabled>Blacklist</button>
    <a href="{{ url_for('views.generate') }}" class="no-deco"><button class="btn btn-primary me-3">Generate</button></a>
    <button class="btn btn-success me-3">Use Combo</button>
</div>
{% endblock %}

dresser/website/templates/history.html
{% extends 'base.html' %}
{% block title %}History{% endblock %}
{% block header %}History{% endblock %}
{% block content %}
<a style="margin-left: 80%;" href="{{ url_for('views.log_gateway', id=0, action='delete_all')}}" class="mt-2 mb-2">Delete All</a>
{% for log in logs %}
    {% if log.event == 'cloth create' %}
        <div class="card mt-4 mb-2 center no-hover">
            <div class="card-header space-between-flex">
                {{ log.event }}
                <a href="{{ url_for('views.log_gateway', id=log.id, action='delete') }}"><button type="button" class="btn-close" aria-label="Close"></button></a>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>New cloth `{{ log.name }}` was created</p>
                <footer class="blockquote-footer">Performed <cite title="Source Title">{{ log.time }}</cite></footer>
            </blockquote>
            </div>
        </div>
    {% elif log.event == 'combo create' %}
        <div class="card mt-4 mb-2 center no-hover">
            <div class="card-header space-between-flex">
                {{ log.event }}
                <a href="{{ url_for('views.log_gateway', id=log.id, action='delete') }}"><button type="button" class="btn-close" aria-label="Close"></button></a>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ log.name }} was created</p>
                <footer class="blockquote-footer">Performed <cite title="Source Title">{{ log.time }}</cite></footer>
            </blockquote>
            </div>
        </div>
    {% elif log.event == 'update' %}
        <div class="card mt-4 mb-2 center no-hover">
            <div class="card-header space-between-flex">
                {{ log.event }}
                <a href="{{ url_for('views.log_gateway', id=log.id, action='delete') }}"><button type="button" class="btn-close" aria-label="Close"></button></a>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>Cloth `{{ log.name }}` was updated</p>
                <footer class="blockquote-footer">Performed <cite title="Source Title">{{ log.time }}</cite></footer>
            </blockquote>
            </div>
        </div>
    {% elif log.event == 'combo update' %}
        <div class="card mt-4 mb-2 center no-hover">
            <div class="card-header space-between-flex">
                {{ log.event }}
                <a href="{{ url_for('views.log_gateway', id=log.id, action='delete') }}"><button type="button" class="btn-close" aria-label="Close"></button></a>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ log.name }} was updated</p>
                <footer class="blockquote-footer">Performed <cite title="Source Title">{{ log.time }}</cite></footer>
            </blockquote>
            </div>
        </div>
    {% elif log.event == 'delete' %}
        <div class="card mt-4 mb-2 center no-hover">
            <div class="card-header space-between-flex">
                {{ log.event }}
                <a href="{{ url_for('views.log_gateway', id=log.id, action='delete') }}"><button type="button" class="btn-close" aria-label="Close"></button></a>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>`{{ log.name }}` was deleted</p>
                <footer class="blockquote-footer">Performed <cite title="Source Title">{{ log.time }}</cite></footer>
            </blockquote>
            </div>
        </div>
    {% elif log.event == 'combo delete' %}
        <div class="card mt-4 mb-2 center no-hover">
            <div class="card-header space-between-flex">
                {{ log.event }}
                <a href="{{ url_for('views.log_gateway', id=log.id, action='delete') }}"><button type="button" class="btn-close" aria-label="Close"></button></a>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ log.name }} was deleted</p>
                <footer class="blockquote-footer">Performed <cite title="Source Title">{{ log.time }}</cite></footer>
            </blockquote>
            </div>
        </div>
    {% endif %}
{% endfor %}
{% endblock %}

dresser/website/templates/home.html
{% extends 'base.html' %}

dresser/website/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block header %}Login{% endblock %}
{% block content %}
<form method="post" class="form-1 m-3">
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary center">Login</button>
</form>

<a href="{{ url_for('auth.signup') }}" class="mt-5 free-center">Dont't have an account?</a>
{% endblock %}